### ISSUE TITLE
Taxonomic clustering: resize panel

### ISSUE THREAD

**Issue by tetomonti** [montilab/Xposome#3]
Would it be possible to give the option to resize the left-most panel (the "Member search", yellow panel)? As it is, it takes a lot of screen space, and it's often empty

**Comment by tetomonti** [comment]
Thanks. Is there a way of making it 'dynamically' resizable? You know, the way you do with, e.g., a table column, where you click on the boundary and move it left or right?

**Comment by RC-88** [comment]
I see. Right now I’m not sure how to make it resizable with fluid grid. I can try and look for a solution for that. Will keep you updates.


Reina C.
