### ISSUE TITLE
Write access

### ISSUE THREAD

**Issue by tetomonti** [montilab/Xposome#4]
Could you please give me write access to the repository? I am trying to update the description pages, but I'm not allowed to push changes. Thanks

**Comment by RC-88** [comment]
Sure thing. I will give access to whole group. Would that okay for you?

Reina C.

**Comment by RC-88** [comment]
Hi Stefano,

I have given read and write access to the xposome group :)

Reina C.

**Comment by tetomonti** [comment]
Hi Reina, 

did you add us as collaborators to the GitHub, or did you simply change the permission on SCC? (The former is needed).

When I try to push changes, I get an error:

smonti@macbook15> pwd
/Users/smonti/research/CBMmetagit/Xposome
smonti@macbook15> git add home.html 
smonti@macbook15> git commit -m 'updated home page'
smonti@macbook15> git push
remote: Permission to RC-88/Xposome.git denied to tetomonti.
fatal: unable to access 'https://github.com/RC-88/Xposome.git/': The requested URL returned error: 403

**Comment by RC-88** [comment]
Hi Stefano,

I haven’t added anyone as collaborators to the GitHub repo. I thought you need the write permission to the scc directory where the application is stored. All the codes and data are stored in /home/xposome/shinyApps. You can make direct changes to the code there, and it will reflect the changes to the portal page without needing to restart the server or affecting the carcinogenome and adipogenome site. I have tested out before. Anyhow, I also sent a collaborator request to you and our group members as well. Let me know if you still have troubles making changes to the Xposome repo. 

Sorry for the confusion!

Reina C.

**Comment by tetomonti** [comment]
Thank you Reina,

The correct way to interact with a GitHub repository is through git commands (pull, push, etc.), for which rw access to the repository is needed. I accepted the invitation. Thanks,

—ste

**Comment by tetomonti** [comment]
Also, between editing sessions, it’s a good idea to ‘git pull’ before starting editing again, to make sure you are working w/ the most up-to-date version. I just committed some changes to the home.html page

—ste

**Comment by RC-88** [comment]
Gotcha! Thanks Stefano! I edit everything in GitHub very manually before (like manuallly browsing and uploading the updated codes and files from my local drive). Hence, It was hard to track my changes.  However, with Adam L’s help, I’ve started to familiarize with some git commands, and that makes my life of editing Xposome repo much easier. I learn a lot from being part of this project :)

Reina C.
